version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app
    container_name: flask_microservice
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: 'True'

  db:
    container_name: flask_postgres
    image: postgres
    restart: always
    volumes:
      - .:/code
    ports:
      - 5432:5432
    env_file:
      - .env

  pgadmin:
    restart: always
    container_name: flask_pgadmin
    image: 'dpage/pgadmin4'
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 5050:80
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis_microservice
    restart: always

  celery:
    restart: always
    image: flask_app
    container_name: celery_microservice
    command: sh -c "cd ./modular/flask_app/ && celery -A my_apps.celery worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - redis
      - web